// <auto-generated />
namespace EFCodeFirstApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202002180922061_.Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
